#!/bin/bash
set -e

. /usr/local/src/install_aur

pacman -S --noconfirm ttf-dejavu otf-fira-code

pacman -S --noconfirm docker docker-compose docker-machine
# systemctl enable docker
usermod -aG docker burkostya
# alternative stack for containers
pacman -S --noconfirm shadow buildah skopeo podman
# enable rootless mode for containers
echo "session    optional   pam_cgfs.so          -c freezer,memory,name=systemd,unified" >> /etc/pam.d/system-login
echo "burkostya:100000:65536" >> /etc/subuid
setcap cap_setuid+ep /usr/bin/newuidmap
echo "burkostya:100000:65536" >> /etc/subgid
setcap cap_setgid+ep /usr/bin/newgidmap

pacman -S --noconfirm --needed libx264

install_aur visual-studio-code-bin
runuser -l burkostya -c "cat $(pwd)/vscode-extensions | xargs -n 1 code --install-extension"

install_aur goland

install_aur postman-bin

pacman -S --noconfirm --needed tldr

pacman -S --noconfirm --needed jq

pacman -S --noconfirm --needed python-xmltodict python-toml yq 
install_aur pup-bin

pacman -S --noconfirm go

pacman -S --noconfirm linux-headers
pacman -S --noconfirm virtualbox virtualbox-host-modules-arch
# install_aur virtualbox-ext-oracle
systemctl enable systemd-modules-load
usermod -aG vboxusers burkostya

# Fonts
# install_aur nerd-fonts-complete

pacman -S --noconfirm --needed vim

# install_aur sos xsos

pacman -S --noconfirm --needed syncthing syncthing-gtk

install_aur alloy
install_aur tla-toolbox

echo -en "y\nn" | trizen -Scc