#!/bin/bash
set -e

# Add our users
groupadd guests
useradd -m -G adm,ftp,games,http,log,rfkill,sys,systemd-journal,users,uucp,wheel,video -s /usr/bin/fish burkostya
useradd -m -G guests,users -s /usr/bin/fish guest

# Set the root password
if [ -n  "$USER_PASSWD" ]; then
    echo "Using user password provided by environment variable..."
    echo -en "$USER_PASSWD\n$USER_PASSWD" | passwd burkostya
else
    echo "Using default user password..."
    echo -en "123\n123" | passwd burkostya
fi

runuser -l burkostya -c "git clone https://github.com/burkostya/dotfiles.git ~/.dotfiles"
runuser -l burkostya -c "cd ~/.dotfiles; and ./install"
# Now that they are installed, removed dotbot to clean up the image.
runuser -l burkostya -c "rm -r ~/.dotfiles/dotbot"

echo "burkostya ALL=(ALL) ALL" >> /etc/sudoers

# runuser -l burkostya -c "git clone https://github.com/oh-my-fish/oh-my-fish.git ~/oh-my-fish"
# runuser -l burkostya -c "cd ~/oh-my-fish; and bin/install --noninteractive"

# trizen -S --noconfirm --noedit fisher

# runuser -l burkostya -c "fisher add edc/bass"

trizen -S --noconfirm --noedit --needed upower kbdlightx1

# extra fonts
pacman -S --noconfirm noto-fonts-extra noto-fonts-emoji

echo -en "y\nn" | pacman -Scc