#!/bin/bash
set -e

# Install Darch
trizen -Sya --noconfirm --noedit darch
# We don't need grub as a bootloader, but we use
# their helper scripts in Darch to generate menu entries.
pacman -S --noconfirm grub
# Enable containerd, which was brought in as a dependency.
systemctl enable containerd
# I store containerd on /var/lib/darch/containerd, because /var/lib/darch
# is an external partition. This way, images are persisted across boots.
mkdir -p /etc/containerd
echo "root = \"/var/lib/darch/containerd\"" > /etc/containerd/config.toml
