kind: pipeline
type: digitalocean
name: archlinux

token:
  from_secret: DO_TOKEN

server:
  image: docker-18-04
  size: s-1vcpu-1gb
  region: nyc3

steps:
- name: setup
  commands:
    - whoami
    - ls -la /usr/bin/sudo
    - mount
    - apt update -y
    - apt upgrade -y
    - apt-get install -y libseccomp-dev wget curl gnupg software-properties-common sudo containerd runc
    - curl -s https://raw.githubusercontent.com/godarch/darch/develop/scripts/install | DARCH_TAG=v0.26.4 bash /dev/stdin
    - mkdir -p /etc/containerd
    - echo 'disabled_plugins = ["cri"]' | tee /etc/containerd/config.toml
    - systemctl start containerd
    - darch version
    - ctr version
    - runc --version

- name: base
  environment:
    DOCKER_LOGIN_USERNAME: 
      from_secret: DOCKER_LOGIN_USERNAME
    DOCKER_LOGIN_PASSWORD: 
      from_secret: DOCKER_LOGIN_PASSWORD
  commands:
    - cd ./thinkpad
    - RECIPE=base ./ci
    - mount
    - ls -la /var/lib || true
    - ls -la /var/lib/darch || true
    - ls -la /var/lib/docker || true

- name: user
  environment:
    DOCKER_LOGIN_USERNAME: 
      from_secret: DOCKER_LOGIN_USERNAME
    DOCKER_LOGIN_PASSWORD: 
      from_secret: DOCKER_LOGIN_PASSWORD
  commands:
    - cd ./thinkpad
    - RECIPE=user ./ci

- name: sec
  environment:
    DOCKER_LOGIN_USERNAME: 
      from_secret: DOCKER_LOGIN_USERNAME
    DOCKER_LOGIN_PASSWORD: 
      from_secret: DOCKER_LOGIN_PASSWORD
  commands:
    - cd ./thinkpad
    - RECIPE=sec ./ci

- name: dev
  environment:
    DOCKER_LOGIN_USERNAME: 
      from_secret: DOCKER_LOGIN_USERNAME
    DOCKER_LOGIN_PASSWORD: 
      from_secret: DOCKER_LOGIN_PASSWORD
  commands:
    - cd ./thinkpad
    - RECIPE=dev ./ci

- name: perf
  environment:
    DOCKER_LOGIN_USERNAME: 
      from_secret: DOCKER_LOGIN_USERNAME
    DOCKER_LOGIN_PASSWORD: 
      from_secret: DOCKER_LOGIN_PASSWORD
  commands:
    - cd ./thinkpad
    - RECIPE=perf ./ci

- name: ops
  environment:
    DOCKER_LOGIN_USERNAME: 
      from_secret: DOCKER_LOGIN_USERNAME
    DOCKER_LOGIN_PASSWORD: 
      from_secret: DOCKER_LOGIN_PASSWORD
  commands:
    - cd ./thinkpad
    - RECIPE=ops ./ci

- name: x
  environment:
    DOCKER_LOGIN_USERNAME: 
      from_secret: DOCKER_LOGIN_USERNAME
    DOCKER_LOGIN_PASSWORD: 
      from_secret: DOCKER_LOGIN_PASSWORD
  commands:
    - cd ./thinkpad
    - RECIPE=x ./ci

- name: audio
  environment:
    DOCKER_LOGIN_USERNAME: 
      from_secret: DOCKER_LOGIN_USERNAME
    DOCKER_LOGIN_PASSWORD: 
      from_secret: DOCKER_LOGIN_PASSWORD
  commands:
    - cd ./thinkpad
    - RECIPE=audio ./ci

- name: i3
  environment:
    DOCKER_LOGIN_USERNAME: 
      from_secret: DOCKER_LOGIN_USERNAME
    DOCKER_LOGIN_PASSWORD: 
      from_secret: DOCKER_LOGIN_PASSWORD
  commands:
    - cd ./thinkpad
    - RECIPE=i3 ./ci

- name: browser
  environment:
    DOCKER_LOGIN_USERNAME: 
      from_secret: DOCKER_LOGIN_USERNAME
    DOCKER_LOGIN_PASSWORD: 
      from_secret: DOCKER_LOGIN_PASSWORD
  commands:
    - cd ./thinkpad
    - RECIPE=browser ./ci

- name: terminal
  environment:
    DOCKER_LOGIN_USERNAME: 
      from_secret: DOCKER_LOGIN_USERNAME
    DOCKER_LOGIN_PASSWORD: 
      from_secret: DOCKER_LOGIN_PASSWORD
  commands:
    - cd ./thinkpad
    - RECIPE=terminal ./ci

- name: social
  environment:
    DOCKER_LOGIN_USERNAME: 
      from_secret: DOCKER_LOGIN_USERNAME
    DOCKER_LOGIN_PASSWORD: 
      from_secret: DOCKER_LOGIN_PASSWORD
  commands:
    - cd ./thinkpad
    - RECIPE=social ./ci

- name: design
  environment:
    DOCKER_LOGIN_USERNAME: 
      from_secret: DOCKER_LOGIN_USERNAME
    DOCKER_LOGIN_PASSWORD: 
      from_secret: DOCKER_LOGIN_PASSWORD
  commands:
    - cd ./thinkpad
    - RECIPE=design ./ci
  # depends_on:
  #   - social

- name: games
  environment:
    DOCKER_LOGIN_USERNAME: 
      from_secret: DOCKER_LOGIN_USERNAME
    DOCKER_LOGIN_PASSWORD: 
      from_secret: DOCKER_LOGIN_PASSWORD
  commands:
    - cd ./thinkpad
    - RECIPE=games ./ci
  # depends_on:
  #   - social

# - name: publish
#   image: plugins/docker
#   settings:
#     username: 
#       from_secret: DOCKER_LOGIN_USERNAME
#     password: 
#       from_secret: DOCKER_LOGIN_PASSWORD
#     repo: burkostya/darch-recipes
#     tags: 
#       - latest
#   when:
#     branch:
#     - master