kind: pipeline
type: docker
name: base


steps:
- name: build
  image: ubuntu:18.04
  volumes:
    - name: dockersock
      path: /var/run
  environment:
    DOCKER_LOGIN_USERNAME: 
      from_secret: DOCKER_LOGIN_USERNAME
    DOCKER_LOGIN_PASSWORD: 
      from_secret: DOCKER_LOGIN_PASSWORD
  commands:
    - apt update -y
    - apt upgrade -y
    - apt-get install -y libseccomp-dev wget curl gnupg software-properties-common sudo
    - wget -O- -q https://github.com/containerd/containerd/releases/download/v1.2.0/containerd-1.2.0.linux-amd64.tar.gz | tar xpz -C /
    - wget https://github.com/opencontainers/runc/releases/download/v1.0.0-rc5/runc.amd64 -O /bin/runc && chmod +x /bin/runc
    - curl -s https://raw.githubusercontent.com/godarch/darch/develop/scripts/install | DARCH_TAG=v0.26.4 bash /dev/stdin
    - mkdir -p /etc/containerd
    - echo 'disabled_plugins = ["cri"]' | tee /etc/containerd/config.toml
    - containerd &
    - apt-get install -y docker.io
    - sleep 5
    - darch version
    - ctr version
    - runc --version
    - chmod a+rwX -R /tmp
    - cd ./thinkpad
    - RECIPE=base ./ci

# - name: publish
#   image: plugins/docker
#   settings:
#     username: 
#       from_secret: DOCKER_LOGIN_USERNAME
#     password: 
#       from_secret: DOCKER_LOGIN_PASSWORD
#     repo: burkostya/arch
#     tags: 
#       - latest
#   when:
#     branch:
#     - master

services:
- name: docker
  image: docker:dind
  privileged: true
  volumes:
    - name: dockersock
      path: /var/run

volumes:
  - name: dockersock
    temp: {}