kind: pipeline
type: digitalocean
name: archlinux

token:
  from_secret: DO_TOKEN

server:
  image: docker-18-04
  size: s-1vcpu-2gb
  region: nyc3

steps:
- name: setup
  commands:
    - whoami
    - ls -la /usr/bin/sudo
    - ls -la /var/lib/dpkg/
    - lsof /var/lib/dpkg/lock-frontend || true
    - sleep 360
    - killall -9 unattended-upgrade || true
    - rm -f /var/lib/dpkg/lock-frontend || true
    - apt update -y
    # - apt upgrade -y
    - apt-get install -y libseccomp-dev wget curl gnupg software-properties-common sudo containerd runc
    - curl -s https://raw.githubusercontent.com/godarch/darch/develop/scripts/install | DARCH_TAG=v0.26.4 bash /dev/stdin
    - mkdir -p /etc/containerd
    - echo 'disabled_plugins = ["cri"]' | tee /etc/containerd/config.toml
    - systemctl start containerd
    - darch version
    - ctr version
    - runc --version
    - mount

- name: dev
  environment:
    DOCKER_LOGIN_USERNAME: 
      from_secret: DOCKER_LOGIN_USERNAME
    DOCKER_LOGIN_PASSWORD: 
      from_secret: DOCKER_LOGIN_PASSWORD
  commands:
    - cd ./thinkpad
    - RECIPE=dev ./ci

# - name: publish
#   image: plugins/docker
#   settings:
#     username: 
#       from_secret: DOCKER_LOGIN_USERNAME
#     password: 
#       from_secret: DOCKER_LOGIN_PASSWORD
#     repo: burkostya/darch-recipes
#     tags: 
#       - latest
#   when:
#     branch:
#     - master