sudo: required
addons:
  apt:
    packages:
      - libseccomp-dev
before_install:
- curl -s https://raw.githubusercontent.com/godarch/darch/develop/scripts/install | sudo DARCH_WITH_RUNTIME="yes" bash /dev/stdin
- sudo containerd &
- darch version
- sudo ctr version
- sudo runc --version

jobs:
  include:
    - stage: base
      script: cd ./thinkpad && RECIPE=base travis_retry ./ci
    - stage: user
      script: cd ./thinkpad && RECIPE=user travis_retry ./ci
    - stage: dev-1
      script: cd ./thinkpad && RECIPE=dev-1 travis_retry ./ci
    - stage: dev-2
      script: cd ./thinkpad && RECIPE=dev-2 travis_retry ./ci
    - stage: x
      script: cd ./thinkpad && RECIPE=x travis_retry ./ci
    - stage: audio
      script: cd ./thinkpad && RECIPE=audio travis_retry ./ci
    - stage: i3
      script: cd ./thinkpad && RECIPE=i3 travis_retry ./ci
    - stage: browser
      script: cd ./thinkpad && RECIPE=browser travis_retry ./ci
    - stage: terminal
      script: cd ./thinkpad && RECIPE=terminal travis_retry ./ci
