sudo: required
addons:
  apt:
    packages:
      - libseccomp-dev
before_install:
- curl -s https://raw.githubusercontent.com/godarch/darch/develop/scripts/install | sudo DARCH_WITH_RUNTIME="yes" bash /dev/stdin
- sudo containerd &
- darch version
- sudo ctr version
- sudo runc --version

jobs:
  include:
    - stage: base
      script: RECIPE=base cd ./thinkpad && ./ci
    - stage: user
      script: RECIPE=user cd ./thinkpad && ./ci
    - stage: dev
      script: RECIPE=dev cd ./thinkpad && ./ci
    - stage: i3
      script: RECIPE=i3 cd ./thinkpad && ./ci
