sudo: required
addons:
  apt:
    packages:
      - libseccomp-dev
before_install:
- curl -s https://raw.githubusercontent.com/godarch/darch/develop/scripts/install | sudo DARCH_WITH_RUNTIME="yes" bash /dev/stdin
- sudo containerd &
- darch version
- sudo ctr version
- sudo runc --version

jobs:
  include:
    - stage: base
      script: cd ./thinkpad && RECIPE=base ./ci
    - stage: user
      script: cd ./thinkpad && RECIPE=user ./ci
    - stage: dev
      script: cd ./thinkpad && RECIPE=dev ./ci
    - stage: i3
      script: cd ./thinkpad && RECIPE=i3 ./ci
