#!/bin/bash
set -e

trizen -S --noconfirm --noedit chromium

trizen -S --noconfirm --noedit atom
runuser -l burkostya -c "apm install (cat $(pwd)/apm_packages)"

trizen -S --noconfirm --noedit keybase-bin

pacman -S --noconfirm go

pacman -S --noconfirm virtualbox-host-modules-arch
pacman -S --noconfirm virtualbox

pacman -S --noconfirm docker docker-compose docker-machine
systemctl enable docker
