#!/bin/bash
set -e

# Initialize the keys
pacman-key --init
pacman-key --populate archlinux

# Resyn the database
pacman -Syy --noconfirm
# Update gpg keys before we install anything else.
pacman -S --noconfirm --needed archlinux-keyring
pacman-key --populate archlinux
# Now update everything.
pacman -Syyu --noconfirm

# Let's update the mirrors.
pacman -S --noconfirm --needed wget sed

wget -q -O- https://www.archlinux.org/mirrorlist/\?country\=RU\&protocol\=https\&ip_version\=4\&use_mirror_status\=on \
  | sed -e "s/#Server/Server/g" \
  > /etc/pacman.d/mirrorlist

echo 'Server = http://mirror.rackspace.com/archlinux/$repo/os/$arch' >> /etc/pacman.d/mirrorlist

pacman -Syyu --noconfirm

pacman -S --noconfirm --needed systemd-resolvconf base base-devel 
pacman -S --noconfirm --needed linux linux-api-headers linux-firmware linux-headers
pacman -S --noconfirm --needed lvm2

pacman -S --noconfirm --needed curl patch
echo "==> source of /usr/bin/makepkg"
cat /usr/bin/makepkg
curl https://gist.githubusercontent.com/pauldotknopf/ff8e986225ab2f264acea1a5bb0c6c5a/raw/5c26a163f7815682793001312b0bd693bebb3d45/makepkg.patch | patch /usr/bin/makepkg
echo "==> source of /usr/bin/makepkg.rej"
cat /usr/bin/makepkg.rej

echo "==> installing trizen"
pacman -S --noconfirm --needed git
git clone https://aur.archlinux.org/trizen.git ~/trizen
pushd ~/trizen
makepkg -si --noconfirm
popd
rm -r ~/trizen

# Timezone
ln -sf ../usr/share/zoneinfo/Europe/Moscow /etc/localtime

# Time sync
pacman -S --noconfirm --needed ntp
systemctl enable ntpd

# Setup the locales.
echo "en_US.UTF-8 UTF-8" > /etc/locale.gen
echo "ru_RU.UTF-8 UTF-8" >> /etc/locale.gen
echo "en_DK.UTF-8 UTF-8" >> /etc/locale.gen
# set system locale
echo "LANG=en_US.UTF-8" > /etc/locale.conf
# use ISO-8601 for time
echo "LC_TIME=en_DK.UTF-8" >> /etc/locale.conf
# use ru locale for users
mkdir -p /etc/skel/.config
echo "LANG=en_US.UTF-8" > /etc/skel/.config/locale.conf
locale-gen

# Use fish, not bash
pacman -S --noconfirm --needed fish

# Set the root password
if [ -n  "$ROOT_PASSWD" ]; then
    echo "Using root password provided by environment variable..."
    echo -en "$ROOT_PASSWD\n$ROOT_PASSWD" | passwd
else
    echo "Using default root password..."
    echo -en "123\n123" | passwd
fi

pacman -S --noconfirm --needed python

pacman -S --noconfirm --needed polkit

pacman -S --noconfirm --needed terminus-font
echo "FONT=ter-p32n" > /etc/vconsole.conf

# install ssh
pacman -S --noconfirm --needed openssh

pacman -S --noconfirm --needed tree

pacman -S --noconfirm --needed cups

systemctl disable man-db.timer

# Enable systemd networking.
cp wired.network /etc/systemd/network/
systemctl enable systemd-networkd
systemctl enable systemd-resolved

pacman -S --noconfirm --needed networkmanager
pacman -S --noconfirm --needed openvpn
cp nodns.conf /etc/NetworkManager/conf.d/
touch /etc/NetworkManager/conf.d/resolv.conf
systemctl enable NetworkManager

echo "nameserver 1.1.1.1" > /etc/resolv.conf

echo "DNSSEC=no" >> /etc/systemd/resolved.conf

pacman -S --noconfirm --needed unzip

echo -en "y\nn" | trizen -Scc