#!/bin/bash
set -e

# This file is used to setup a base Arch machine
# that will be used solely for booting Darch images.
# Run this script from within the Arch live cd.

disk=/dev/nvme0n1

parted -s $disk \
        mklabel gpt \
        mkpart ESP fat32 1MiB 1GiB \
        set 1 boot on \
        mkpart primary 1GiB 100%

sleep 5

mkfs.fat -F32 "${disk}p1"

pvcreate "${disk}p2"
vgcreate main "${disk}p2"

declare -A volumes=(
        ["darchconfig"]="100MB" 
        ["darchlib"]="40GiB" 
        ["root"]="10GiB" 
        ["home"]="100GiB" 
        ["nm"]="4MiB" 
        ["ssh"]="8MiB" 
        ["chromium"]="600MiB" 
        ["localshare"]="8GiB" 
        ["go"]="50GiB" 
        ["src"]="50GiB" 
        ["dbeaver"]="8MiB" 
        ["dbeaver-drivers"]="32MiB" 
        ["dockerlib"]="50GiB" 
        ["gnupg"]="4MiB" 
        ["pass"]="32MiB" 
        ["steam"]="10GiB" 
        ["unity3d"]="32MiB" 
        ["gravit"]="128MiB" 
        ["yed"]="32MiB" 
        ["terraform"]="512MiB" 
        ["k8s"]="64MiB" 
        ["helm"]="64MiB" 
        ["vpn"]="8MiB" 
        ["goland"]="1GiB" 
        ["slack"]="256MiB" 
        ["firefox"]="1GiB" 
        ["robot3t"]="128MiB" 
        ["mongo-compass"]="128MiB" 
        ["vscode"]="256MiB" 
)

for name in "${!volumes[@]}"; do
        lvcreate -L ${volumes[$name]} main -n $name
        mkfs.ext4 /dev/main/${name}
done

mount /dev/mapper/main-root /mnt
mkdir /mnt/boot
mount "${disk}p1" /mnt/boot
mkdir -p /mnt/etc/darch
mount /dev/mapper/main-darchconfig /mnt/etc/darch
mkdir -p /mnt/var/lib/darch
mount /dev/mapper/main-darchlib /mnt/var/lib/darch
mkdir -p /mnt/home
mount /dev/mapper/main-home /mnt/home
