#!/bin/bash
set -e

# This file is used to setup a base Arch machine
# that will be used solely for booting Darch images.
# Run this script from within the Arch live cd.

disk=/dev/nvme0n1

parted -s $disk \
        mklabel gpt \
        mkpart ESP fat32 1MiB 1GiB \
        set 1 boot on \
        mkpart primary 1GiB 100%

sleep 5

mkfs.fat -F32 "${disk}p1"

pvcreate "${disk}p2"
vgcreate main "${disk}p2"
lvcreate -L 100MB main -n darchconfig
lvcreate -L 40GiB main -n darchlib
lvcreate -L 10GiB main -n root
lvcreate -L 100GiB main -n home
lvcreate -L 4MiB main -n nm
lvcreate -L 8MiB main -n ssh
lvcreate -L 600MiB main -n chromium
lvcreate -L 2GiB main -n localshare
lvcreate -L 50GiB main -n go
lvcreate -L 8MiB main -n dbeaver
lvcreate -L 32MiB main -n dbeaver-drivers
lvcreate -L 50GiB main -n dockerlib

mkfs.ext4 /dev/mapper/main-darchconfig
mkfs.ext4 /dev/mapper/main-darchlib
mkfs.ext4 /dev/mapper/main-root
mkfs.ext4 /dev/mapper/main-home
mkfs.ext4 /dev/mapper/main-nm
mkfs.ext4 /dev/mapper/main-ssh
mkfs.ext4 /dev/mapper/main-chromium
mkfs.ext4 /dev/mapper/main-localshare
mkfs.ext4 /dev/mapper/main-go
mkfs.ext4 /dev/mapper/main-dbeaver
mkfs.ext4 /dev/mapper/main-dbeaver--drivers
mkfs.ext4 /dev/mapper/main-dockerlib

mount /dev/mapper/main-root /mnt
mkdir /mnt/boot
mount "${disk}p1" /mnt/boot
mkdir -p /mnt/etc/darch
mount /dev/mapper/main-darchconfig /mnt/etc/darch
mkdir -p /mnt/var/lib/darch
mount /dev/mapper/main-darchlib /mnt/var/lib/darch
mkdir -p /mnt/home
mount /dev/mapper/main-home /mnt/home
