#!/bin/bash
set -e

pacman -S --noconfirm jq

pacman -S --noconfirm go
# vgo bug https://github.com/golang/go/issues/24773
# mkdir /usr/lib/go/api
# touch /usr/lib/go/api/go1.10.txt

# install gvm
runuser -l burkostya -c "curl -s -S -L https://raw.githubusercontent.com/moovweb/gvm/6ecd46d8b58c18f2a7bd5a1ab604cb57443cd35c/binscripts/gvm-installer | bash"

pacman -S --noconfirm linux-headers
pacman -S --noconfirm virtualbox virtualbox-host-modules-arch
# trizen -S --noconfirm --noedit virtualbox-ext-oracle
systemctl enable systemd-modules-load
usermod -aG vboxusers burkostya

# Fonts
# trizen -S --noconfirm --noedit nerd-fonts-complete

pacman -S --noconfirm vim

pacman -S --noconfirm dbeaver
pacman -S --noconfirm dbeaver-plugin-office dbeaver-plugin-svg-format

# trizen -S --noconfirm --noedit sos xsos

pacman -S --noconfirm terraform

pacman -S --noconfirm ansible

pacman -S --noconfirm rsync

trizen -S --noconfirm --noedit python-pip
pip3 install netaddr

pacman -S --noconfirm tinc
