#!/bin/bash
set -e

. /usr/local/src/install_aur

install_aur perf-tools
pacman -S --noconfirm --needed clang llvm netperf iperf ethtool powertop
pacman -S --noconfirm --needed strace
install_aur bcc
install_aur bpftrace-git
install_aur fatrace
install_aur pygtk
install_aur swig
install_aur trace-cmd
install_aur flamegraph
install_aur ctop

echo -en "y\nn" | trizen -Scc