#!/bin/bash
set -e

. /usr/local/src/install_aur

# Resyn the database
pacman -Sy --noconfirm

echo "==> installing i3"
pacman -S --noconfirm --needed i3 compton xorg-xinit

echo "==> installing desktop bar"
gpg --search-keys A1774C1B37DC1DCEDB65EE469B8450B91D1362C1
gpg --lsign-key A1774C1B37DC1DCEDB65EE469B8450B91D1362C1
pacman -S --noconfirm --needed dmenu
install_aur j4-dmenu-desktop
install_aur polybar

echo "==> install clipboard tools"
install_aur unclutter-xfixes-git 
pacman -S --noconfirm --needed autocutsel

pacman -S --noconfirm --needed redshift

pacman -S --noconfirm --needed xorg-xwininfo xorg-xprop
cp i3-window-criteria /usr/local/bin/

pacman -S --noconfirm --needed peek

echo -en "y\nn" | trizen -Scc