#!/bin/bash
set -e

. /usr/local/src/install_aur

# X stage
pacman -S --noconfirm --needed xf86-video-intel
pacman -S --noconfirm --needed xorg-server xorg-xrandr xorg-xdpyinfo
pacman -S --noconfirm --needed xorg-xinput xorg-xbacklight
pacman -S --noconfirm --needed xbindkeys

# pacman -S --noconfirm udisks2 udiskie

cp 30-touchpad.conf /etc/X11/xorg.conf.d/

cp 30-trackpoint.conf /etc/X11/xorg.conf.d/
cp 30-trackpoint.hwdb /etc/udev/hwdb.d/

cp wifi /usr/local/bin/

pacman -S --noconfirm --needed imagemagick

cp i3lock.service /etc/systemd/system/i3lock@.service
systemctl enable i3lock@burkostya

usermod -aG audio burkostya

## audio stage
# Enable audio
pacman -S --noconfirm --needed pulseaudio pulseaudio-alsa
pacman -S --noconfirm --needed pavucontrol

# Add ability to connect bluetooth headsets
pacman -S --noconfirm --needed pulseaudio-bluetooth bluez-utils

pacman -S --noconfirm --needed sonic-pi
pacman -S --noconfirm --needed cadence

# i3 stage

# Resyn the database
pacman -Sy --noconfirm

echo "==> installing i3"
pacman -S --noconfirm --needed i3 compton xorg-xinit

echo "==> installing desktop bar"
runuser -l burkostya -c "gpg --recv-keys A1774C1B37DC1DCEDB65EE469B8450B91D1362C1" && \
pacman -S --noconfirm --needed dmenu
install_aur j4-dmenu-desktop
install_aur polybar
# fonts for polybar
pacman -S --noconfirm bdf-unifont ttf-nerd-fonts-symbols otf-font-awesome
install_aur ttf-unifont
install_aur siji-git ttf-material-design-icons-webfont

echo "==> install clipboard tools"
install_aur unclutter-xfixes-git 
pacman -S --noconfirm --needed autocutsel

pacman -S --noconfirm --needed redshift

pacman -S --noconfirm --needed xorg-xwininfo xorg-xprop
cp i3-window-criteria /usr/local/bin/

pacman -S --noconfirm --needed peek

echo -en "y\nn" | trizen -Scc