#!/bin/bash
set -e

. /usr/local/src/install_aur

pacman -S --noconfirm docker docker-compose docker-machine
# systemctl enable docker
usermod -aG docker burkostya
# alternative stack for containers
pacman -S --noconfirm shadow buildah skopeo podman
# enable rootless mode for containers
echo "session    optional   pam_cgfs.so          -c freezer,memory,name=systemd,unified" >> /etc/pam.d/system-login
echo "burkostya:100000:65536" >> /etc/subuid
setcap cap_setuid+ep /usr/bin/newuidmap
echo "burkostya:100000:65536" >> /etc/subgid
setcap cap_setgid+ep /usr/bin/newgidmap

pacman -S --noconfirm iotop sysdig

pacman -S --noconfirm mosh

echo "Timespamp: $(date)"

pacman -S --noconfirm --needed terraform
install_aur minikube-bin
install_aur kubectl-bin 
install_aur kubernetes-helm-bin
install_aur kustomize-bin
install_aur draft-bin

pacman -S --noconfirm --needed ansible

install_aur jsonnet

pacman -S --noconfirm --needed rsync

echo "Timespamp: $(date)"

pacman -S --noconfirm --needed python-pip
pip3 install netaddr

pacman -S --noconfirm --needed tinc

install_aur robo3t-bin

pacman -S --noconfirm --needed dbeaver
pacman -S --noconfirm --needed dbeaver-plugin-office dbeaver-plugin-svg-format

echo -en "y\nn" | trizen -Scc

echo "Timespamp: $(date)"