#!/bin/bash
set -e

. /usr/local/src/install_aur

pacman -S --noconfirm iotop sysdig

pacman -S --noconfirm mosh

echo "Timespamp: $(date)"

pacman -S --noconfirm --needed terraform
install_aur minikube-bin
install_aur kubectl-bin 
install_aur kubernetes-helm-bin
install_aur kustomize-bin
install_aur draft-bin

pacman -S --noconfirm --needed ansible

install_aur jsonnet

pacman -S --noconfirm --needed rsync

echo "Timespamp: $(date)"

pacman -S --noconfirm --needed python-pip
pip3 install netaddr

pacman -S --noconfirm --needed tinc

echo -en "y\nn" | trizen -Scc

echo "Timespamp: $(date)"