#!/bin/bash
set -e

IMAGES=$(sudo darch recipes build-dep)
TAG=`date +"%Y-%m-%d-%H%M%S"`

BASE=$(echo $IMAGES | cut -d ' ' -f1)

RECIPE=${RECIPE:-$BASE}

PARENT=$(darch recipes parents $RECIPE 2>&1 | head -n1 | cut -d ' ' -f3)

INTERNAL_IMAGES=${IMAGES//$'\n'/|}

if [[ $PARENT =~ ^($INTERNAL_IMAGES)$ ]]; then
  PARENT="docker.io/burkostya/darch-thinkpad-$PARENT"
fi

echo "pulling $PARENT"
darch images pull $PARENT
echo "building $RECIPE"
sudo darch recipes build -t latest -p "docker.io/burkostya/darch-thinkpad-" $RECIPE
echo "taging $RECIPE:$TAG"
sudo darch images tag docker.io/burkostya/darch-thinkpad-$RECIPE:latest docker.io/burkostya/darch-thinkpad-$RECIPE:$TAG