#!/bin/bash
set -e

IMAGES=$(sudo darch recipes build-dep)
TAG=`date +"%Y-%m-%d-%H%M%S"`
TAG_LATEST="latest"

if [[ "$BRANCH" != "master" ]]; then
  TAG="$BRANCH$TAG"
  TAG_LATEST="$BRANCH$TAG_LATEST"
fi

BASE=$(echo $IMAGES | cut -d ' ' -f1)

RECIPE=${RECIPE:-$BASE}

PARENT=$(darch recipes parents $RECIPE 2>&1 | head -n1 | cut -d ' ' -f3)

INTERNAL_IMAGES=${IMAGES//$'\n'/|}

if [[ $PARENT =~ ^($INTERNAL_IMAGES)$ ]]; then
  PARENT="docker.io/burkostya/darch-thinkpad-$PARENT"
fi

echo "pulling $PARENT"
sudo darch images pull $PARENT
echo "building $RECIPE"
sudo darch recipes build -t $TAG_LATEST -p "docker.io/burkostya/darch-thinkpad-" $RECIPE
echo "taging $RECIPE:$TAG"
sudo darch images tag docker.io/burkostya/darch-thinkpad-$RECIPE:$TAG_LATEST docker.io/burkostya/darch-thinkpad-$RECIPE:$TAG