# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ "dm-snapshot" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems = {
    "/" = { 
      device = "/dev/disk/by-uuid/383ba9fe-b51e-44cf-9cf9-24332d4e3d2c";
      fsType = "ext4";
    };
    "/home/burkostya/src" = {
      device = "/dev/main/src";
      options = [
        "defaults" "relatime" "noauto" "x-systemd.automount"
      ];
    };
    "/home/burkostya/.ssh/keys" = {
      device = "/dev/main/ssh";
      options = [
        "defaults" "relatime" "noauto" "x-systemd.automount" "ro" "noload"
      ];
    };
  };

  swapDevices = [ ];

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  # high-resolution display
  hardware.video.hidpi.enable = lib.mkDefault true;

  hardware.bluetooth.enable = true;
  services.blueman.enable = true;

  hardware.pulseaudio.enable = true;
}