#!/bin/bash
set -e

# This file is used to setup a base Arch machine
# that will be used solely for booting Darch images.
# Run this script from within the Arch live cd.

usbdisk=/dev/sdc

parted -s $usbdisk \
        mklabel gpt \
        mkpart ESP fat32 1MiB 200MiB \
        set 1 boot on \
        mkpart primary 200MiB 100%

mkfs.fat -F32 "${usbdisk}1"

pvcreate "${usbdisk}2"
vgcreate main "${usbdisk}2"
lvcreate -L 2GiB main -n archlive
lvcreate -l 100%FREE main -n data

mkfs.ext4 /dev/mapper/main-archlive
mkfs.ext4 /dev/mapper/main-data

mount /dev/mapper/main-archlive /mnt
mkdir /mnt/boot
mount "${usbdisk}1" /mnt/boot

grub-install --target x86_64-efi --efi-directory /mnt/boot --boot-directory=/mnt/boot --removable

echo "live" > /mnt/etc/.machine
