#!/bin/bash
set -e

trizen -S --noconfirm --noedit --needed gravit-designer-bin
trizen -S --noconfirm --noedit --needed archlinux-java-run yed
pacman -S --noconfirm --needed dia
pacman -S --noconfirm --needed graphviz

echo -en "y\nn" | trizen -Scc