#!/bin/bash
set -e

# This file is used to setup a base Arch machine
# that will be used solely for booting Darch images.
# Run this script from within the Arch live cd.

parted -s /dev/sda \
        mklabel gpt \
        mkpart ESP fat32 1MiB 1GiB \
        set 1 boot on \
        mkpart primary 1GiB 100%

mkfs.fat -F32 /dev/sda1

pvcreate /dev/sda2
vgcreate vg00 /dev/sda2
lvcreate -L 100MB vg00 -n darchconfig
lvcreate -L 20GiB vg00 -n darchlib
lvcreate -L 10GiB vg00 -n root
lvcreate -l 100%FREE vg00 -n home

mkfs.ext4 /dev/mapper/vg00-darchconfig
mkfs.ext4 /dev/mapper/vg00-darchlib
mkfs.ext4 /dev/mapper/vg00-root
mkfs.ext4 /dev/mapper/vg00-home

mount /dev/mapper/vg00-root /mnt
mkdir -p /mnt/etc/darch
mount /dev/mapper/vg00-darchconfig /mnt/etc/darch
mkdir -p /mnt/var/lib/darch
mount /dev/mapper/vg00-darchlib /mnt/var/lib/darch
mkdir /mnt/boot
mount /dev/sda1 /mnt/boot
mkdir /mnt/home
mount /dev/mapper/vg00-home /mnt/home

echo "vbox" > /mnt/etc/.machine
