#!/bin/bash
set -e

pacman -S --noconfirm ttf-dejavu

# pacman -S --noconfirm noto-fonts-extra noto-fonts-emoji

pacman -S --noconfirm docker docker-compose docker-machine
# systemctl enable docker
usermod -aG docker burkostya

pacman -S --noconfirm libx264

trizen -S --noconfirm --noedit visual-studio-code-bin
runuser -l burkostya -c "cat $(pwd)/vscode-extensions | xargs -n 1 code --install-extension"

trizen -S --noconfirm --noedit postman-bin

pacman -S --noconfirm iotop sysdig

pacman -S --noconfirm mosh

trizen -S --noconfirm --noedit tldr