#!/bin/bash
set -e

pacman -Sy
pacman -S --noconfirm --needed firefox
pacman -S --noconfirm --needed chromium

echo "export BROWSER=firefox" > /etc/profile.d/browser.sh
xdg-mime default firefox.desktop x-scheme-handler/https
xdg-mime default firefox.desktop x-scheme-handler/http

echo -en "y\nn" | trizen -Scc