#!/bin/bash
set -e

pacman -Sy
pacman -S --noconfirm --needed chromium
pacman -S --noconfirm --needed firefox

echo "export BROWSER=chromium" > /etc/profile.d/browser.sh
xdg-mime default chromium.desktop x-scheme-handler/https
xdg-mime default chromium.desktop x-scheme-handler/http

echo -en "y\nn" | trizen -Scc