#!/bin/bash
set -e

. ../common

# Setup the locales.
echo "en_US.UTF-8 UTF-8" > /etc/locale.gen
echo "ru_RU.UTF-8 UTF-8" >> /etc/locale.gen
# set system locale
echo "LANG=en_US.UTF-8" > /etc/locale.conf
# use ISO-8601 for time
echo "LC_TIME=en_DK.UTF-8" >> /etc/locale.conf
# use ru locale for users
mkdir -p /mnt/etc/skel/.config
echo "LANG=ru_RU.UTF-8" > /mnt/etc/skel/.config/locale.conf
locale-gen

# Set the root password
if [ -n  "$ROOT_PASSWD" ]; then
    echo "Using root password provided by environment variable..."
    echo -en "$ROOT_PASSWD\n$ROOT_PASSWD" | passwd
else
    echo "Using default root password..."
    echo -en "password\npassword" | passwd
fi

# Use fish, not bash
install_packages fish

# Add our users
groupadd guests
useradd -m -G adm,ftp,games,http,log,rfkill,sys,systemd-journal,users,uucp,wheel -s /usr/bin/fish burkostya
useradd -m -G guests,users -s /usr/bin/fish guest

# TODO: restrict access to su/sudo commands for non-wheel users

# Set the root password
if [ -n  "$USER_PASSWD" ]; then
    echo "Using user password provided by environment variable..."
    echo -en "$USER_PASSWD\n$USER_PASSWD" | passwd pknopf
else
    echo "Using default user password..."
    echo -en "password\npassword" | passwd pknopf
fi

install_packages python
runuser -l burkostya -c "git clone https://github.com/burkostya/dotfiles.git ~/.dotfiles"
runuser -l burkostya -c "cd ~/.dotfiles && ./install"
# Now that they are installed, removed dotbot to clean up the image.
runuser -l burkostya -c "rm -r ~/.dotfiles/dotbot"

# Setup sudo
install_packages sudo
echo "burkostya ALL=(ALL) ALL" >> /etc/sudoers

# Enable ssh
install_packages openssh

# Fonts
install_aur_package ttf-ms-fonts
install_aur_package nerd-fonts-complete

# Timezone
rm /etc/localtime
ln -s ../usr/share/zoneinfo/Europe/Moscow /etc/localtime

# Time sync
install_packages ntp
systemctl enable ntpd

git clone https://github.com/oh-my-fish/oh-my-fish
cd oh-my-fish
bin/install --offline
