#!/bin/bash
set -e

usermod -aG audio burkostya

# Enable audio
pacman -S --noconfirm --needed pulseaudio
pacman -S --noconfirm --needed pavucontrol

pacman -S --noconfirm --needed sonic-pi
pacman -S --noconfirm --needed cadence

trizen -Scc --noconfirm