#!/bin/bash
set -e

usermod -aG audio burkostya

# Enable audio
pacman -S --noconfirm --needed pulseaudio pulseaudio-alsa
pacman -S --noconfirm --needed pavucontrol

# Add ability to connect bluetooth headsets
pacman -S --noconfirm --needed pulseaudio-bluetooth bluez-utils

pacman -S --noconfirm --needed sonic-pi
pacman -S --noconfirm --needed cadence

echo -en "y\nn" | trizen -Scc
