name: build

on: push

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - run: whoami
      - run: ls -la /usr/bin/sudo
      - run: sudo apt update -y
      - run: ps aux | grep -i apt
      - run: sudo apt upgrade -y
      - run: sudo apt-get install -y libseccomp-dev wget curl gnupg software-properties-common sudo containerd runc
      - run: curl -s https://raw.githubusercontent.com/godarch/darch/develop/scripts/install | DARCH_TAG=v0.26.4 sudo bash /dev/stdin
      - run: sudo mkdir -p /etc/containerd
      - run: echo 'disabled_plugins = ["cri"]' | sudo tee /etc/containerd/config.toml
      - run: sudo systemctl start containerd
      - run: darch version
      - run: sudo ctr version
      - run: sudo runc --version
      - run: sudo mount