#!/bin/bash
set -e

# This file is used to setup a base Arch machine
# that will be used solely for booting Darch images.
# Run this script from within the Arch live cd.

# 128GB
main=/dev/sda
# 240GB
secondary=/dev/sdb

parted -s $main \
        mklabel gpt \
        mkpart ESP fat32 1MiB 1GiB \
        set 1 boot on \
        mkpart primary 1GiB 100%

parted -s $secondary \
        mkpart primary 0% 100%

mkfs.fat -F32 "${main}1"

pvcreate "${main}2" "${secondary}1"

vgcreate main "${main}2"
lvcreate -L 10GiB main -n root
lvcreate -L 100MB main -n darchconfig

vgcreate persist "${secondary}1"
lvcreate -l 40GiB persist -n darchlib
lvcreate -L 40GiB persist -n containers
lvcreate -L 40GiB persist -n vboxes

mkfs.ext4 /dev/mapper/main-root
mkfs.ext4 /dev/mapper/main-darchconfig

mkfs.ext4 /dev/mapper/persist-darchlib
mkfs.ext4 /dev/mapper/persist-containers
mkfs.ext4 /dev/mapper/persist-vboxes

mount /dev/mapper/main-root /mnt
mkdir /mnt/boot
mount "${main}1" /mnt/boot
mkdir -p /mnt/etc/darch
mount /dev/mapper/main-darchconfig /mnt/etc/darch
mkdir -p /mnt/var/lib/darch
mount /dev/mapper/main-darchlib /mnt/var/lib/darch
